return {
	PlaceObj('ModItemCode', {
		'name', "OR_ReloadCombatAction",
		'CodeFileName', "Code/OR_ReloadCombatAction.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "OR_Misc",
		'CodeFileName', "Code/OR_Misc.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "OR_HighlightWeaponsForAmmo",
		'CodeFileName', "Code/OR_HighlightWeaponsForAmmo.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "OR_MoveItem",
		'CodeFileName', "Code/OR_MoveItem.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "OR_Unit",
		'CodeFileName', "Code/OR_Unit.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "OR_Firearm",
		'CodeFileName', "Code/OR_Firearm.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "ReloadUtils",
		'CodeFileName', "Code/ReloadUtils.lua",
	}),
	PlaceObj('ModItemFolder', {
		'name', "Options and Setup",
	}, {
		PlaceObj('ModItemCode', {
			'name', "SETUP_BobbyRays",
			'CodeFileName', "Code/SETUP_BobbyRays.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "SETUP_MsgDefs",
			'CodeFileName', "Code/SETUP_MsgDefs.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "SETUP_MagsItemDefinition",
			'CodeFileName', "Code/SETUP_MagsItemDefinition.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "SETUP_ModOptions",
			'CodeFileName', "Code/SETUP_ModOptions.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "SETUP_AddPlatformAndMagazineToWeapons",
			'CodeFileName', "Code/SETUP_AddPlatformAndMagazineToWeapons.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "SETUP_Config",
			'CodeFileName', "Code/SETUP_Config.lua",
		}),
		PlaceObj('ModItemOptionChoice', {
			'name', "RevisedMagDropChance",
			'DisplayName', "Mag Drop Chance",
			'Help', "How often the mags will drop",
			'DefaultValue', "10",
			'ChoiceList', {
				"1",
				"5",
				"10",
				"20",
				"25",
				"50",
				"75",
				"100",
			},
		}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "Compatibility",
	}, {
		PlaceObj('ModItemCode', {
			'name', "CMP_RealCalibers",
			'CodeFileName', "Code/CMP_RealCalibers.lua",
		}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "Mags",
	}, {
		PlaceObj('ModItemWeaponComponent', {
			Cost = 2,
			DisplayName = T(109952508927, --[[ModItemWeaponComponent MagNormal DisplayName]] "Default Mag"),
			Icon = "UI/Icons/Upgrades/default_magazine",
			ModificationDifficulty = -25,
			Slot = "Magazine",
			Visuals = {
				PlaceObj('WeaponComponentVisual', {
					Entity = "WeaponAttA_Magazine_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "HiPower",
					Entity = "WeaponAttA_MagazineBHP_01",
					Icon = "UI/Icons/Upgrades/BHP_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Bereta92",
					Entity = "WeaponAttA_MagazineBeretta_01",
					Icon = "UI/Icons/Upgrades/beretta_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Glock18",
					Entity = "WeaponAttA_MagazineGlock18_01",
					Icon = "UI/Icons/Upgrades/glock_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "DesertEagle",
					Entity = "WeaponAttA_MagazineDesertEagle_01",
					Icon = "UI/Icons/Upgrades/deserteagle_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AKSU",
					Entity = "WeaponAttA_MagazineAKS74U_01",
					Icon = "UI/Icons/Upgrades/AK74_Bakelite_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP5",
					Entity = "WeaponAttA_MagazineMP5_01",
					Icon = "UI/Icons/Upgrades/mp5_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP5K",
					Entity = "WeaponAttA_MagazineMP5_01",
					Icon = "UI/Icons/Upgrades/mp5_mag_normal",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP40",
					Entity = "WeaponAttA_MagazineMP40_01",
					Icon = "Mod/URkxyfE/magpictures/MP40_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "UZI",
					Entity = "WeaponAttA_MagazineUzi_01",
					Icon = "Mod/URkxyfE/magpictures/uzi_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "LionRoar",
					Entity = "WeaponAttA_MagazineUzi_01",
					Icon = "Mod/URkxyfE/magpictures/uzi_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M4Commando",
					Entity = "WeaponAttA_MagazineCAR15_02",
					Icon = "Mod/URkxyfE/magpictures/m4_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "RPK74",
					Entity = "WeaponAttA_MagazineAK47_01",
					Icon = "UI/Icons/Upgrades/AK47_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AK47",
					Entity = "WeaponAttA_MagazineAK47_01",
					Icon = "UI/Icons/Upgrades/AK47_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "FAMAS",
					Entity = "WeaponAttA_MagazineFAMAS",
					Icon = "UI/Icons/Upgrades/expanded_FAMAS_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AR15",
					Entity = "WeaponAttA_MagazineCAR15_02",
					Icon = "Mod/URkxyfE/magpictures/m4_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M16A2",
					Entity = "WeaponAttA_MagazineCAR15_02",
					Icon = "Mod/URkxyfE/magpictures/m4_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AUG",
					Entity = "WeaponAttA_MagazineSteyr_01",
					Icon = "UI/Icons/Upgrades/steyr_AUG_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "FNFAL",
					Entity = "WeaponAttA_MagazineFNFal_01",
					Icon = "Mod/URkxyfE/magpictures/fnfal_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Galil",
					Entity = "WeaponAttA_MagazineGalil_01",
					Icon = "Mod/URkxyfE/magpictures/galil_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Galil_FlagHill",
					Entity = "WeaponAttA_MagazineGalil_01",
					Icon = "Mod/URkxyfE/magpictures/galil_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "G36",
					Entity = "WeaponAttA_MagazineHKG36_01",
					Icon = "UI/Icons/Upgrades/G36_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AK74",
					Entity = "WeaponAttA_MagazineAK47_01",
					Icon = "UI/Icons/Upgrades/AK74_Bakelite_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M14SAW",
					Entity = "WeaponAttA_MagazineM14_Standard",
					Icon = "UI/Icons/Upgrades/M14_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "GoldenGun",
					Entity = "WeaponAttA_MagazineM14_Standard",
					Icon = "UI/Icons/Upgrades/M14_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "PSG1",
					Entity = "WeaponAttA_MagazinePSG_01",
					Icon = "Mod/URkxyfE/magpictures/g3_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "DragunovSVD",
					Entity = "WeaponAttA_MagazineDragunov_01",
					Icon = "Mod/URkxyfE/magpictures/dragunov_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "BarretM82",
					Entity = "WeaponAttA_MagazineBarrettM82_01",
					Icon = "Mod/URkxyfE/magpictures/M82_mag_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "HK21",
					Entity = "WeaponAttA_MagazinePSG_01",
					Icon = "Mod/URkxyfE/magpictures/g3_normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AA12",
					Entity = "WeaponAttA_MagazineAA12_01",
					Icon = "Mod/URkxyfE/magpictures/aa_12normal.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Gewehr98",
					Entity = "WeaponAttA_MagazineM24_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M24Sniper",
					Entity = "WeaponAttA_MagazineM24_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Winchester1894",
					Entity = "WeaponAttA_MagazineM24_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
			},
			group = "Clip",
			id = "MagNormal",
		}),
		PlaceObj('ModItemWeaponComponent', {
			Cost = 15,
			DisplayName = T(629963472411, --[[ModItemWeaponComponent MagLarge DisplayName]] "Expanded Mag"),
			Icon = "UI/Icons/Upgrades/galil_magazine_large",
			ModificationDifficulty = 0,
			Slot = "Magazine",
			Visuals = {
				PlaceObj('WeaponComponentVisual', {
					Entity = "WeaponAttA_Magazine_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "HiPower",
					Entity = "WeaponAttA_MagazineBHP_02",
					Icon = "UI/Icons/Upgrades/BHP_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Bereta92",
					Entity = "WeaponAttA_MagazineBeretta_02",
					Icon = "UI/Icons/Upgrades/beretta_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Glock18",
					Entity = "WeaponAttA_MagazineGlock18_02",
					Icon = "UI/Icons/Upgrades/glock_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "DesertEagle",
					Entity = "WeaponAttA_MagazineDesertEagle_02",
					Icon = "UI/Icons/Upgrades/desertEagle_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AKSU",
					Entity = "WeaponAttA_MagazineAKS74U_02",
					Icon = "UI/Icons/Upgrades/expanded_AK74_bakelite_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP5",
					Entity = "WeaponAttA_MagazineMP5_02",
					Icon = "UI/Icons/Upgrades/mp5_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP5K",
					Entity = "WeaponAttA_MagazineMP5_02",
					Icon = "UI/Icons/Upgrades/mp5_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "MP40",
					Entity = "WeaponAttA_MagazineMP40_02",
					Icon = "UI/Icons/Upgrades/expanded_MP40_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "UZI",
					Entity = "WeaponAttA_MagazineUzi_02",
					Icon = "UI/Icons/Upgrades/uzi_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "LionRoar",
					Entity = "WeaponAttA_MagazineUzi_02",
					Icon = "UI/Icons/Upgrades/uzi_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M4Commando",
					Entity = "WeaponAttA_MagazineM16_01",
					Icon = "UI/Icons/Upgrades/m16_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "RPK74",
					Entity = "WeaponAttA_MagazineAK47_02",
					Icon = "UI/Icons/Upgrades/expanded_AK47_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AK47",
					Entity = "WeaponAttA_MagazineAK47_02",
					Icon = "UI/Icons/Upgrades/expanded_AK47_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AR15",
					Entity = "WeaponAttA_MagazineM16_01",
					Icon = "UI/Icons/Upgrades/m16_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AUG",
					Entity = "WeaponAttA_MagazineSteyr_02",
					Icon = "UI/Icons/Upgrades/expanded_steyr_AUG_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "FNFAL",
					Entity = "WeaponAttA_MagazineFNFal_02",
					Icon = "Mod/URkxyfE/magpictures/fnfal_expanded.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Galil",
					Entity = "WeaponAttA_MagazineGalil_02",
					Icon = "UI/Icons/Upgrades/galil_magazine_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "Galil_FlagHill",
					Entity = "WeaponAttA_MagazineGalil_02",
					Icon = "UI/Icons/Upgrades/galil_magazine_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "G36",
					Entity = "WeaponAttA_MagazineHKG36_01",
					Icon = "UI/Icons/Upgrades/G36_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AK74",
					Entity = "WeaponAttA_MagazineAK47_02",
					Icon = "UI/Icons/Upgrades/expanded_AK74_bakelite_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M14SAW",
					Entity = "WeaponAttA_MagazineM14_Extended",
					Icon = "UI/Icons/Upgrades/expanded_M14_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "GoldenGun",
					Entity = "WeaponAttA_MagazineM14_Extended",
					Icon = "UI/Icons/Upgrades/expanded_M14_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "PSG1",
					Entity = "WeaponAttA_MagazinePSG_02",
					Icon = "Mod/URkxyfE/magpictures/g3_expanded.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "HK21",
					Entity = "WeaponAttA_MagazineHK21_01",
					Icon = "Mod/URkxyfE/magpictures/g3_expanded.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "BarretM82",
					Entity = "WeaponAttA_MagazineBarrettM82_02",
					Icon = "Mod/URkxyfE/magpictures/M82_mag_large.png",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "M16A2",
					Entity = "WeaponAttA_MagazineM16_01",
					Icon = "UI/Icons/Upgrades/m16_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AA12",
					Entity = "WeaponAttA_MagazineAA12_02",
					Icon = "UI/Icons/Upgrades/aa12_mag_drum",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "FNMinimi",
					Entity = "WeaponAttA_MagazineFNMinimi_01",
					Icon = "UI/Icons/Upgrades/machine_gun_box_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
			},
			group = "Clip",
			id = "MagLarge",
		}),
		PlaceObj('ModItemWeaponComponent', {
			Cost = 25,
			DisplayName = T(968707157913, --[[ModItemWeaponComponent MagLarger DisplayName]] "LMG and MG Magazines"),
			Icon = "UI/Icons/Upgrades/galil_magazine_large",
			ModificationDifficulty = 0,
			Slot = "Magazine",
			Visuals = {
				PlaceObj('WeaponComponentVisual', {
					Entity = "WeaponAttA_Magazine_01",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "AK47",
					Entity = "WeaponAttA_MagazineRPK74_03",
					Icon = "UI/Icons/Upgrades/RPK74_drum_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "RPK74",
					Entity = "WeaponAttA_MagazineRPK74_03",
					Icon = "UI/Icons/Upgrades/RPK74_drum_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "G36",
					Entity = "WeaponAttA_MagazineHKG36_02",
					Icon = "UI/Icons/Upgrades/expanded_drum_G36_magazine",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "HK21",
					Entity = "WeaponAttA_MagazineHK21_02",
					Icon = "UI/Icons/Upgrades/hk21_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "PSG1",
					Entity = "WeaponAttA_MagazineHK21_02",
					Icon = "UI/Icons/Upgrades/hk21_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
				PlaceObj('WeaponComponentVisual', {
					ApplyTo = "FNMinimi",
					Entity = "WeaponAttA_MagazineFNMinimi_02",
					Icon = "UI/Icons/Upgrades/fnminimi_mag_large",
					Slot = "Magazine",
					param_bindings = false,
				}),
			},
			group = "Clip",
			id = "MagLarger",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "BHPMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/BHP_mag_normal",
			'DisplayName', T(346509557267, --[[ModItemInventoryItemCompositeDef BHPMagazine DisplayName]] "BHP Magazine"),
			'DisplayNamePlural', T(419595371394, --[[ModItemInventoryItemCompositeDef BHPMagazine DisplayNamePlural]] "BHP Magazines"),
			'Description', T(778816736927, --[[ModItemInventoryItemCompositeDef BHPMagazine Description]] "Standard HiPower magazine"),
			'AdditionalHint', T(788297269809, --[[ModItemInventoryItemCompositeDef BHPMagazine AdditionalHint]] "9mm"),
			'Cost', 99,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "HiPower",
			'MagazineSize', 13,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Pistol",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "BHPMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/BHP_mag_large",
			'DisplayName', T(842225174706, --[[ModItemInventoryItemCompositeDef BHPMagazineLarge DisplayName]] "BHP Extended Magazine"),
			'DisplayNamePlural', T(140643348672, --[[ModItemInventoryItemCompositeDef BHPMagazineLarge DisplayNamePlural]] "BHP Extended Magazines"),
			'Description', T(736603968083, --[[ModItemInventoryItemCompositeDef BHPMagazineLarge Description]] "Extended HiPower magazine"),
			'AdditionalHint', T(243534740691, --[[ModItemInventoryItemCompositeDef BHPMagazineLarge AdditionalHint]] "9mm"),
			'Cost', 199,
			'CanAppearInShop', true,
			'Tier', 2,
			'MaxStock', 6,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "HiPower",
			'MagazineSize', 20,
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Pistol",
			'MagReloadCosts', 14000,
			'MagUnloadCosts', 7000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "BerettaMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/beretta_mag_normal",
			'DisplayName', T(864507774814, --[[ModItemInventoryItemCompositeDef BerettaMagazine DisplayName]] "Beretta Magazine"),
			'DisplayNamePlural', T(416317621832, --[[ModItemInventoryItemCompositeDef BerettaMagazine DisplayNamePlural]] "Beretta Magazines"),
			'Description', T(702680870997, --[[ModItemInventoryItemCompositeDef BerettaMagazine Description]] "Standard Beretta magazine"),
			'AdditionalHint', T(971567342173, --[[ModItemInventoryItemCompositeDef BerettaMagazine AdditionalHint]] "9mm"),
			'Cost', 99,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Beretta",
			'MagazineSize', 15,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Pistol",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "BerettaMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/beretta_mag_large",
			'DisplayName', T(197162323047, --[[ModItemInventoryItemCompositeDef BerettaMagazineLarge DisplayName]] "Extended Beretta Magazine"),
			'DisplayNamePlural', T(314509090245, --[[ModItemInventoryItemCompositeDef BerettaMagazineLarge DisplayNamePlural]] "Extended Beretta Magazines"),
			'Description', T(773460172429, --[[ModItemInventoryItemCompositeDef BerettaMagazineLarge Description]] "Extended Beretta magazine"),
			'AdditionalHint', T(820491098536, --[[ModItemInventoryItemCompositeDef BerettaMagazineLarge AdditionalHint]] "9mm"),
			'Cost', 199,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Beretta",
			'MagazineSize', 24,
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Pistol",
			'MagReloadCosts', 16000,
			'MagUnloadCosts', 8000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "GlockMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/glock_mag_normal",
			'DisplayName', T(626992530087, --[[ModItemInventoryItemCompositeDef GlockMagazine DisplayName]] "Glock Magazine"),
			'DisplayNamePlural', T(248787786056, --[[ModItemInventoryItemCompositeDef GlockMagazine DisplayNamePlural]] "Glock Magazines"),
			'Description', T(238763143918, --[[ModItemInventoryItemCompositeDef GlockMagazine Description]] "Standard Glock magazine"),
			'AdditionalHint', T(193087859533, --[[ModItemInventoryItemCompositeDef GlockMagazine AdditionalHint]] "9mm"),
			'Cost', 99,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Glock",
			'MagazineSize', 15,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Pistol",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "GlockMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/glock_mag_large",
			'DisplayName', T(396993697244, --[[ModItemInventoryItemCompositeDef GlockMagazineLarge DisplayName]] "Extended Glock Magazine"),
			'DisplayNamePlural', T(420296576604, --[[ModItemInventoryItemCompositeDef GlockMagazineLarge DisplayNamePlural]] "Extended Glock Magazines"),
			'Description', T(697240786727, --[[ModItemInventoryItemCompositeDef GlockMagazineLarge Description]] "Extended Glock magazine"),
			'AdditionalHint', T(767077445666, --[[ModItemInventoryItemCompositeDef GlockMagazineLarge AdditionalHint]] "9mm"),
			'Cost', 199,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Glock",
			'MagazineSize', 24,
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Pistol",
			'MagReloadCosts', 16000,
			'MagUnloadCosts', 8000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "DesertEagleMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/deserteagle_mag_normal",
			'DisplayName', T(915668483121, --[[ModItemInventoryItemCompositeDef DesertEagleMagazine DisplayName]] "Desert Eagle Magazine"),
			'DisplayNamePlural', T(776313716592, --[[ModItemInventoryItemCompositeDef DesertEagleMagazine DisplayNamePlural]] "Desert Eagle Magazines"),
			'Description', T(610426682203, --[[ModItemInventoryItemCompositeDef DesertEagleMagazine Description]] "Standard Desert Eagle Magazine"),
			'AdditionalHint', T(860923252701, --[[ModItemInventoryItemCompositeDef DesertEagleMagazine AdditionalHint]] ".44 Magnum"),
			'Cost', 100,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Glock",
			'MagazineSize', 8,
			'Caliber', "44CAL",
			'Modification', "MagNormal",
			'Type', "Pistol",
			'MagReloadCosts', 8000,
			'MagUnloadCosts', 4000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "DesertEagleMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/desertEagle_mag_large",
			'DisplayName', T(419231552909, --[[ModItemInventoryItemCompositeDef DesertEagleMagazineLarge DisplayName]] "Extended Desert Eagle Magazine "),
			'DisplayNamePlural', T(289773868535, --[[ModItemInventoryItemCompositeDef DesertEagleMagazineLarge DisplayNamePlural]] "Extended Desert Eagle Magazines"),
			'Description', T(979476090414, --[[ModItemInventoryItemCompositeDef DesertEagleMagazineLarge Description]] "Extended Desert Eagle Magazine"),
			'AdditionalHint', T(482787970218, --[[ModItemInventoryItemCompositeDef DesertEagleMagazineLarge AdditionalHint]] ".44 Magnum"),
			'Cost', 100,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "PistolMags",
			'Platform', "Glock",
			'MagazineSize', 13,
			'Caliber', "44CAL",
			'Modification', "MagLarge",
			'Type', "Pistol",
			'MagReloadCosts', 12000,
			'MagUnloadCosts', 6000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "MP5Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/mp5_mag_normal",
			'DisplayName', T(380067518258, --[[ModItemInventoryItemCompositeDef MP5Magazine DisplayName]] "Small MP5 Magazine"),
			'DisplayNamePlural', T(855060268788, --[[ModItemInventoryItemCompositeDef MP5Magazine DisplayNamePlural]] "Small MP5 Magazines"),
			'Description', T(183827799514, --[[ModItemInventoryItemCompositeDef MP5Magazine Description]] "Small MP5 Magazine"),
			'AdditionalHint', T(934759206980, --[[ModItemInventoryItemCompositeDef MP5Magazine AdditionalHint]] "9mm"),
			'Cost', 249,
			'CanAppearInShop', true,
			'MaxStock', 4,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "MP5",
			'MagazineSize', 15,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Pistol",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "MP5MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/mp5_mag_large",
			'DisplayName', T(270265120737, --[[ModItemInventoryItemCompositeDef MP5MagazineLarge DisplayName]] "MP5 Magazine"),
			'DisplayNamePlural', T(997289885960, --[[ModItemInventoryItemCompositeDef MP5MagazineLarge DisplayNamePlural]] " MP5 Magazines"),
			'Description', T(519441584306, --[[ModItemInventoryItemCompositeDef MP5MagazineLarge Description]] "Standard MP5 Magazine"),
			'AdditionalHint', T(611728180814, --[[ModItemInventoryItemCompositeDef MP5MagazineLarge AdditionalHint]] "9mm"),
			'Cost', 399,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "MP5",
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 18000,
			'MagUnloadCosts', 9000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "MP40Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/MP40_mag_normal.png",
			'DisplayName', T(670950948161, --[[ModItemInventoryItemCompositeDef MP40Magazine DisplayName]] "MP40 Magazine"),
			'DisplayNamePlural', T(106021205921, --[[ModItemInventoryItemCompositeDef MP40Magazine DisplayNamePlural]] "MP40 Magazines"),
			'Description', T(954219452157, --[[ModItemInventoryItemCompositeDef MP40Magazine Description]] "MP40 magazine"),
			'AdditionalHint', T(367126411924, --[[ModItemInventoryItemCompositeDef MP40Magazine AdditionalHint]] "9mm"),
			'Cost', 349,
			'CanAppearInShop', true,
			'MaxStock', 5,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "MP40",
			'MagazineSize', 32,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 18000,
			'MagUnloadCosts', 9000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "MP40MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_MP40_magazine",
			'DisplayName', T(269409484176, --[[ModItemInventoryItemCompositeDef MP40MagazineLarge DisplayName]] "Extended MP40 Magazine"),
			'DisplayNamePlural', T(777100244676, --[[ModItemInventoryItemCompositeDef MP40MagazineLarge DisplayNamePlural]] "Extended MP40 Magazines"),
			'Description', T(214388360902, --[[ModItemInventoryItemCompositeDef MP40MagazineLarge Description]] "Extended MP40 magazine"),
			'AdditionalHint', T(204120668109, --[[ModItemInventoryItemCompositeDef MP40MagazineLarge AdditionalHint]] "9mm"),
			'Cost', 449,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "MP40",
			'MagazineSize', 42,
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "UZIMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/uzi_mag_normal.png",
			'DisplayName', T(366742892294, --[[ModItemInventoryItemCompositeDef UZIMagazine DisplayName]] "UZI Magazine"),
			'DisplayNamePlural', T(113647653707, --[[ModItemInventoryItemCompositeDef UZIMagazine DisplayNamePlural]] "UZI Magazines"),
			'Description', T(858187468628, --[[ModItemInventoryItemCompositeDef UZIMagazine Description]] "UZI magazine for 9mm rounds"),
			'AdditionalHint', T(915101743767, --[[ModItemInventoryItemCompositeDef UZIMagazine AdditionalHint]] "9mm"),
			'Cost', 299,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "UZI",
			'MagazineSize', 25,
			'Caliber', "9mm",
			'Modification', "MagNormal",
			'Type', "Pistol",
			'MagReloadCosts', 16000,
			'MagUnloadCosts', 8000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "UZIMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/uzi_mag_large",
			'DisplayName', T(599852600977, --[[ModItemInventoryItemCompositeDef UZIMagazineLarge DisplayName]] "Extended UZI Magazine"),
			'DisplayNamePlural', T(837264443885, --[[ModItemInventoryItemCompositeDef UZIMagazineLarge DisplayNamePlural]] "Extended UZI Magazines"),
			'Description', T(898883046149, --[[ModItemInventoryItemCompositeDef UZIMagazineLarge Description]] "Extended UZI magazine for 9mm rounds"),
			'AdditionalHint', T(229254702009, --[[ModItemInventoryItemCompositeDef UZIMagazineLarge AdditionalHint]] "9mm"),
			'Cost', 399,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "SMGMags",
			'Platform', "UZI",
			'MagazineSize', 40,
			'Caliber', "9mm",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "STANAGMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/m4_mag_normal.png",
			'DisplayName', T(297754309466, --[[ModItemInventoryItemCompositeDef STANAGMagazine DisplayName]] "STANAG Magazine"),
			'DisplayNamePlural', T(280496470685, --[[ModItemInventoryItemCompositeDef STANAGMagazine DisplayNamePlural]] "STANAG Magazines"),
			'Description', T(319440802232, --[[ModItemInventoryItemCompositeDef STANAGMagazine Description]] "Standard STANAG Magazine for 5.56 round"),
			'AdditionalHint', T(760146909250, --[[ModItemInventoryItemCompositeDef STANAGMagazine AdditionalHint]] "5.56mm"),
			'Cost', 499,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'MagazineSize', 20,
			'Caliber', "556",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 18000,
			'MagUnloadCosts', 9000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "STANAGMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/m16_magazine",
			'DisplayName', T(470988243825, --[[ModItemInventoryItemCompositeDef STANAGMagazineLarge DisplayName]] "Extended STANAG Magazine"),
			'DisplayNamePlural', T(702075557653, --[[ModItemInventoryItemCompositeDef STANAGMagazineLarge DisplayNamePlural]] "Extended STANAG Magazines"),
			'Description', T(173560130045, --[[ModItemInventoryItemCompositeDef STANAGMagazineLarge Description]] "Extended STANAG Magazine for 5.56 round"),
			'AdditionalHint', T(676533745102, --[[ModItemInventoryItemCompositeDef STANAGMagazineLarge AdditionalHint]] "5.56mm"),
			'Cost', 599,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Caliber', "556",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AK47Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/AK47_magazine",
			'DisplayName', T(197994505354, --[[ModItemInventoryItemCompositeDef AK47Magazine DisplayName]] "AK47 Magazine"),
			'DisplayNamePlural', T(256521754595, --[[ModItemInventoryItemCompositeDef AK47Magazine DisplayNamePlural]] "AK47 Magazines"),
			'Description', T(303524049456, --[[ModItemInventoryItemCompositeDef AK47Magazine Description]] "Standard AK 47 Magazine for 7.62 round"),
			'AdditionalHint', T(413761107136, --[[ModItemInventoryItemCompositeDef AK47Magazine AdditionalHint]] "7.62mm"),
			'Cost', 349,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AK762",
			'Caliber', "762WP",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AK47MagazineMagLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_AK47_magazine",
			'DisplayName', T(746528289938, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarge DisplayName]] "AK47 Magazine Large"),
			'DisplayNamePlural', T(381725812126, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarge DisplayNamePlural]] "AK47 Magazines Large"),
			'Description', T(579300305909, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarge Description]] "Expanded AK 47 Magazine for 7.62 round used as default for RPK"),
			'AdditionalHint', T(477705021835, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarge AdditionalHint]] "7.62mm"),
			'Cost', 449,
			'CanAppearInShop', true,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AK762",
			'MagazineSize', 45,
			'Caliber', "762WP",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 28000,
			'MagUnloadCosts', 14000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AK47MagazineMagLarger",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/RPK74_drum_magazine",
			'DisplayName', T(288540638613, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarger DisplayName]] "RPK Drum Magazine"),
			'DisplayNamePlural', T(491809893307, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarger DisplayNamePlural]] "RPK Drum Magazines"),
			'Description', T(623103865336, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarger Description]] "RPK Drum Magazine"),
			'AdditionalHint', T(843188582960, --[[ModItemInventoryItemCompositeDef AK47MagazineMagLarger AdditionalHint]] "7.62mm"),
			'Cost', 699,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "MGMags",
			'Platform', "AK762",
			'MagazineSize', 100,
			'Caliber', "762WP",
			'Modification', "MagLarger",
			'Type', "Rifle",
			'ExtraAPCosts', 2000,
			'MagReloadCosts', 50000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "FAMASMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_FAMAS_magazine",
			'DisplayName', T(397807620775, --[[ModItemInventoryItemCompositeDef FAMASMagazine DisplayName]] "FAMAS Magazine"),
			'DisplayNamePlural', T(468811747930, --[[ModItemInventoryItemCompositeDef FAMASMagazine DisplayNamePlural]] "FAMAS Magazines"),
			'Description', T(836930527108, --[[ModItemInventoryItemCompositeDef FAMASMagazine Description]] "Standard FAMAS Magazine for the 5.56mm round"),
			'AdditionalHint', T(934391465309, --[[ModItemInventoryItemCompositeDef FAMASMagazine AdditionalHint]] "5.56mm"),
			'Cost', 449,
			'CanAppearInShop', true,
			'MaxStock', 6,
			'RestockWeight', 90,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "FAMAS",
			'MagazineSize', 25,
			'Caliber', "556",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 20000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AUGMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/steyr_AUG_magazine",
			'DisplayName', T(680307895949, --[[ModItemInventoryItemCompositeDef AUGMagazine DisplayName]] "AUG Magazine"),
			'DisplayNamePlural', T(841724768345, --[[ModItemInventoryItemCompositeDef AUGMagazine DisplayNamePlural]] "AUG Magazines"),
			'Description', T(408645536277, --[[ModItemInventoryItemCompositeDef AUGMagazine Description]] "Standard AUG Magazine"),
			'AdditionalHint', T(226052432153, --[[ModItemInventoryItemCompositeDef AUGMagazine AdditionalHint]] "5.56mm"),
			'Cost', 499,
			'CanAppearInShop', true,
			'Tier', 2,
			'MaxStock', 4,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AUG",
			'Caliber', "556",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "AUGMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_steyr_AUG_magazine",
			'DisplayName', T(436741511026, --[[ModItemInventoryItemCompositeDef AUGMagazineLarge DisplayName]] "Extended AUG Magazine"),
			'DisplayNamePlural', T(107220770627, --[[ModItemInventoryItemCompositeDef AUGMagazineLarge DisplayNamePlural]] "Extended AUG Magazines"),
			'Description', T(486012822384, --[[ModItemInventoryItemCompositeDef AUGMagazineLarge Description]] "Extended AUG Magazine"),
			'AdditionalHint', T(802232149831, --[[ModItemInventoryItemCompositeDef AUGMagazineLarge AdditionalHint]] "5.56mm"),
			'Cost', 599,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AUG",
			'MagazineSize', 42,
			'Caliber', "556",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 28000,
			'MagUnloadCosts', 14000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "FNFALMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/fnfal_normal.png",
			'DisplayName', T(650432458305, --[[ModItemInventoryItemCompositeDef FNFALMagazine DisplayName]] "FNFAL Magazine"),
			'DisplayNamePlural', T(994364457929, --[[ModItemInventoryItemCompositeDef FNFALMagazine DisplayNamePlural]] "FNFAL Magazines"),
			'Description', T(479791052605, --[[ModItemInventoryItemCompositeDef FNFALMagazine Description]] "Standard FNFAL Magazine for the 7.62mm round"),
			'AdditionalHint', T(383494416041, --[[ModItemInventoryItemCompositeDef FNFALMagazine AdditionalHint]] "7.62mm NATO"),
			'Cost', 449,
			'CanAppearInShop', true,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "FNFAL",
			'MagazineSize', 20,
			'Caliber', "762NATO",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 18000,
			'MagUnloadCosts', 9000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "FNFALMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/fnfal_expanded.png",
			'DisplayName', T(591226334130, --[[ModItemInventoryItemCompositeDef FNFALMagazineLarge DisplayName]] "FNFAL Magazine"),
			'DisplayNamePlural', T(123423196816, --[[ModItemInventoryItemCompositeDef FNFALMagazineLarge DisplayNamePlural]] "FNFAL Magazines"),
			'Description', T(137608804060, --[[ModItemInventoryItemCompositeDef FNFALMagazineLarge Description]] "Standard FNFAL Magazine for the 7.62mm round"),
			'AdditionalHint', T(574318320309, --[[ModItemInventoryItemCompositeDef FNFALMagazineLarge AdditionalHint]] "7.62mm NATO"),
			'Cost', 599,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "FNFAL",
			'Caliber', "762NATO",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 24000,
			'MagUnloadCosts', 12000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "GalilMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/galil_mag_normal.png",
			'DisplayName', T(546949415062, --[[ModItemInventoryItemCompositeDef GalilMagazine DisplayName]] "Galil Magazine"),
			'DisplayNamePlural', T(737487578825, --[[ModItemInventoryItemCompositeDef GalilMagazine DisplayNamePlural]] "Galil Magazines"),
			'Description', T(469860253168, --[[ModItemInventoryItemCompositeDef GalilMagazine Description]] "Galil Magazine for the 7.62mm NATO"),
			'AdditionalHint', T(586839273520, --[[ModItemInventoryItemCompositeDef GalilMagazine AdditionalHint]] "7.62mm NATO"),
			'Cost', 449,
			'CanAppearInShop', true,
			'Tier', 2,
			'MaxStock', 4,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "Galil",
			'MagazineSize', 25,
			'Caliber', "762NATO",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 20000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "GalilMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/galil_magazine_large",
			'DisplayName', T(155161482218, --[[ModItemInventoryItemCompositeDef GalilMagazineLarge DisplayName]] "Extended Galil Magazine"),
			'DisplayNamePlural', T(758170231146, --[[ModItemInventoryItemCompositeDef GalilMagazineLarge DisplayNamePlural]] "Extended Galil Magazines"),
			'Description', T(580123573901, --[[ModItemInventoryItemCompositeDef GalilMagazineLarge Description]] "Extended Galil Magazine"),
			'AdditionalHint', T(392948848099, --[[ModItemInventoryItemCompositeDef GalilMagazineLarge AdditionalHint]] "7.62mm NATO"),
			'Cost', 549,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "Galil",
			'MagazineSize', 40,
			'Caliber', "762NATO",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 28000,
			'MagUnloadCosts', 14000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "G36MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/G36_magazine",
			'DisplayName', T(241702335876, --[[ModItemInventoryItemCompositeDef G36MagazineLarge DisplayName]] "G36 Magazine"),
			'DisplayNamePlural', T(216085238153, --[[ModItemInventoryItemCompositeDef G36MagazineLarge DisplayNamePlural]] "G36 Magazines"),
			'Description', T(353746051262, --[[ModItemInventoryItemCompositeDef G36MagazineLarge Description]] "Standard Magazine for G36"),
			'AdditionalHint', T(490528401416, --[[ModItemInventoryItemCompositeDef G36MagazineLarge AdditionalHint]] "5.56mm"),
			'Cost', 499,
			'CanAppearInShop', true,
			'Tier', 2,
			'MaxStock', 4,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "G36",
			'Caliber', "556",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "G36MagazineQuick",
			'object_class', "Mag",
			'ScrapParts', 6,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/quick_G36_magazine",
			'DisplayName', T(858466109050, --[[ModItemInventoryItemCompositeDef G36MagazineQuick DisplayName]] "G36 Magazine"),
			'DisplayNamePlural', T(799412004845, --[[ModItemInventoryItemCompositeDef G36MagazineQuick DisplayNamePlural]] "G36 Magazines"),
			'Description', T(114366044624, --[[ModItemInventoryItemCompositeDef G36MagazineQuick Description]] "Quick Magazine for G36"),
			'AdditionalHint', T(310218274541, --[[ModItemInventoryItemCompositeDef G36MagazineQuick AdditionalHint]] "5.56mm"),
			'Cost', 100,
			'CanBeConsumed', false,
			'Platform', "G36",
			'MagazineSize', 60,
			'Caliber', "556",
			'Modification', "MagQuick",
			'Type', "Rifle",
		}),
		PlaceObj('ModItemRecipeDef', {
			Difficulty = 0,
			Ingredients = {
				PlaceObj('RecipeIngredient', {
					'item', "G36MagazineLarge",
				}),
				PlaceObj('RecipeIngredient', {
					'item', "G36MagazineLarge",
				}),
			},
			ResultItems = {
				PlaceObj('RecipeIngredient', {
					'item', "G36MagazineQuick",
				}),
			},
			group = "Clip",
			id = "G36QuickMag",
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "G36MagazineLarger",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_drum_G36_magazine",
			'DisplayName', T(421339476130, --[[ModItemInventoryItemCompositeDef G36MagazineLarger DisplayName]] "G36 Drum Magazine"),
			'DisplayNamePlural', T(255695106893, --[[ModItemInventoryItemCompositeDef G36MagazineLarger DisplayNamePlural]] "G36 Drum Magazines"),
			'Description', T(956629558068, --[[ModItemInventoryItemCompositeDef G36MagazineLarger Description]] "Drum Magazine for G36"),
			'AdditionalHint', T(134197212893, --[[ModItemInventoryItemCompositeDef G36MagazineLarger AdditionalHint]] "5.56mm"),
			'Cost', 799,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "MGMags",
			'Platform', "G36",
			'MagazineSize', 100,
			'Caliber', "556",
			'Modification', "MagLarger",
			'Type', "Large",
			'ExtraAPCosts', 2000,
			'MagReloadCosts', 50000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AK74Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/AK74_Bakelite_magazine",
			'DisplayName', T(944939391173, --[[ModItemInventoryItemCompositeDef AK74Magazine DisplayName]] "AK74 Magazine"),
			'DisplayNamePlural', T(176064522679, --[[ModItemInventoryItemCompositeDef AK74Magazine DisplayNamePlural]] "AK74 Magazines"),
			'Description', T(730820981523, --[[ModItemInventoryItemCompositeDef AK74Magazine Description]] "Standard AK 74 Magazine for 5.45 round also used by AKSU"),
			'AdditionalHint', T(284899607406, --[[ModItemInventoryItemCompositeDef AK74Magazine AdditionalHint]] "5.45mm"),
			'Cost', 399,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AK762",
			'Caliber', "762WP",
			'Modification', "MagNormalFine",
			'Type', "Rifle",
			'MagReloadCosts', 22000,
			'MagUnloadCosts', 11000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "AK74MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_AK74_bakelite_magazine",
			'DisplayName', T(263923953709, --[[ModItemInventoryItemCompositeDef AK74MagazineLarge DisplayName]] "AK74 Expanded Magazine"),
			'DisplayNamePlural', T(138791525079, --[[ModItemInventoryItemCompositeDef AK74MagazineLarge DisplayNamePlural]] "AK74 Expanded Magazines"),
			'Description', T(598530279861, --[[ModItemInventoryItemCompositeDef AK74MagazineLarge Description]] "Expanded AK 74 Magazine for 5.45 round"),
			'AdditionalHint', T(241880890162, --[[ModItemInventoryItemCompositeDef AK74MagazineLarge AdditionalHint]] "5.45mm"),
			'Cost', 549,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "AK762",
			'MagazineSize', 45,
			'Caliber', "762WP",
			'Modification', "MagLargeFine",
			'Type', "Rifle",
			'MagReloadCosts', 30000,
			'MagUnloadCosts', 15000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "M14Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/M14_magazine",
			'DisplayName', T(419258536921, --[[ModItemInventoryItemCompositeDef M14Magazine DisplayName]] "M14 Magazine"),
			'DisplayNamePlural', T(748039484649, --[[ModItemInventoryItemCompositeDef M14Magazine DisplayNamePlural]] "M14 Magazines"),
			'Description', T(307163251257, --[[ModItemInventoryItemCompositeDef M14Magazine Description]] "M14 Magazin"),
			'AdditionalHint', T(593147163304, --[[ModItemInventoryItemCompositeDef M14Magazine AdditionalHint]] "7.62mm NATO"),
			'Cost', 349,
			'CanAppearInShop', true,
			'MaxStock', 5,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "M14",
			'MagazineSize', 10,
			'Caliber', "762NATO",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 12000,
			'MagUnloadCosts', 6000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "M14MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/expanded_M14_magazine",
			'DisplayName', T(330983046837, --[[ModItemInventoryItemCompositeDef M14MagazineLarge DisplayName]] "Extended M14 Magazine"),
			'DisplayNamePlural', T(517758768368, --[[ModItemInventoryItemCompositeDef M14MagazineLarge DisplayNamePlural]] "Extended M14 Magazines"),
			'Description', T(229239844615, --[[ModItemInventoryItemCompositeDef M14MagazineLarge Description]] "Extended M14 Magazin"),
			'AdditionalHint', T(649358195253, --[[ModItemInventoryItemCompositeDef M14MagazineLarge AdditionalHint]] "7.62mm NATO"),
			'Cost', 449,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 70,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "M14",
			'MagazineSize', 20,
			'Caliber', "762NATO",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 20000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "HKG3Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/g3_normal.png",
			'DisplayName', T(851026653117, --[[ModItemInventoryItemCompositeDef HKG3Magazine DisplayName]] "PSG1 Magazine"),
			'DisplayNamePlural', T(265908131581, --[[ModItemInventoryItemCompositeDef HKG3Magazine DisplayNamePlural]] "PSG1 Magazines"),
			'Description', T(684199504018, --[[ModItemInventoryItemCompositeDef HKG3Magazine Description]] "PSG1 Magazin"),
			'AdditionalHint', T(702883456097, --[[ModItemInventoryItemCompositeDef HKG3Magazine AdditionalHint]] "7.62mm NATO"),
			'Cost', 349,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "HKG3",
			'MagazineSize', 5,
			'Caliber', "762NATO",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 8000,
			'MagUnloadCosts', 4000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "HKG3MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/g3_expanded.png",
			'DisplayName', T(906480252330, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarge DisplayName]] "HK21 Magazine"),
			'DisplayNamePlural', T(254435009704, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarge DisplayNamePlural]] "HK21 Magazines"),
			'Description', T(565422177836, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarge Description]] "HK21 magazine for 7.62 NATO round"),
			'AdditionalHint', T(743853421491, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarge AdditionalHint]] "7.62mm NATO"),
			'Cost', 449,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "HKG3",
			'MagazineSize', 20,
			'Caliber', "762NATO",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 18000,
			'MagUnloadCosts', 9000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "HKG3MagazineLarger",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/hk21_mag_large",
			'DisplayName', T(943859599380, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarger DisplayName]] "HK21 Magazine large"),
			'DisplayNamePlural', T(617753593554, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarger DisplayNamePlural]] "HK21 Magazines large"),
			'Description', T(662486512433, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarger Description]] "Large HK21 magazine for 7.62 NATO round"),
			'AdditionalHint', T(298144314218, --[[ModItemInventoryItemCompositeDef HKG3MagazineLarger AdditionalHint]] "7.62mm NATO"),
			'Cost', 699,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "MGMags",
			'Platform', "HKG3",
			'MagazineSize', 100,
			'Caliber', "762NATO",
			'Modification', "MagLarger",
			'Type', "Large",
			'ExtraAPCosts', 4000,
			'MagReloadCosts', 55000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "SVDMagazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/dragunov_mag_normal",
			'DisplayName', T(694366750538, --[[ModItemInventoryItemCompositeDef SVDMagazine DisplayName]] "SVD Magazine"),
			'DisplayNamePlural', T(350262067108, --[[ModItemInventoryItemCompositeDef SVDMagazine DisplayNamePlural]] "SVD Magazines"),
			'Description', T(680220331718, --[[ModItemInventoryItemCompositeDef SVDMagazine Description]] "Standard SVD magazine"),
			'AdditionalHint', T(757416315650, --[[ModItemInventoryItemCompositeDef SVDMagazine AdditionalHint]] "7.62mm WP"),
			'Cost', 449,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "SVD",
			'MagazineSize', 10,
			'Caliber', "762WP",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 12000,
			'MagUnloadCosts', 6000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "BarretM82Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/M82_mag_normal.png",
			'DisplayName', T(480663085177, --[[ModItemInventoryItemCompositeDef BarretM82Magazine DisplayName]] "BarretM82 Magazine"),
			'DisplayNamePlural', T(332358561336, --[[ModItemInventoryItemCompositeDef BarretM82Magazine DisplayNamePlural]] "BarretM82 Magazines"),
			'Description', T(470374936555, --[[ModItemInventoryItemCompositeDef BarretM82Magazine Description]] "Standard BarretM82 magazine"),
			'AdditionalHint', T(184473771816, --[[ModItemInventoryItemCompositeDef BarretM82Magazine AdditionalHint]] "50BMG"),
			'Cost', 499,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "BarretM82",
			'MagazineSize', 5,
			'Caliber', "50BMG",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 12000,
			'MagUnloadCosts', 6000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "BarretM82MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/M82_mag_large.png",
			'DisplayName', T(346444667903, --[[ModItemInventoryItemCompositeDef BarretM82MagazineLarge DisplayName]] "BarretM82 Magazine"),
			'DisplayNamePlural', T(928637668402, --[[ModItemInventoryItemCompositeDef BarretM82MagazineLarge DisplayNamePlural]] "BarretM82 Magazines"),
			'Description', T(933482280309, --[[ModItemInventoryItemCompositeDef BarretM82MagazineLarge Description]] "Standard BarretM82 magazine"),
			'AdditionalHint', T(588048423283, --[[ModItemInventoryItemCompositeDef BarretM82MagazineLarge AdditionalHint]] "50BMG"),
			'Cost', 899,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "RifleMags",
			'Platform', "BarretM82",
			'MagazineSize', 10,
			'Caliber', "50BMG",
			'Modification', "MagLarge",
			'Type', "Rifle",
			'MagReloadCosts', 20000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "FNMinimiMagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/machine_gun_box_magazine",
			'DisplayName', T(601950860008, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarge DisplayName]] "FNMinimi Magazine"),
			'DisplayNamePlural', T(586364397393, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarge DisplayNamePlural]] "FNMinimi Magazines"),
			'Description', T(985346745546, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarge Description]] "Standard FNMinimi magazine for 5.56 round"),
			'AdditionalHint', T(853659506906, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarge AdditionalHint]] "5.56mm"),
			'Cost', 599,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "MGMags",
			'Platform', "SAW",
			'MagazineSize', 100,
			'Caliber', "556",
			'Modification', "MagLarger",
			'Type', "Large",
			'ExtraAPCosts', 4000,
			'MagReloadCosts', 55000,
			'MagUnloadCosts', 10000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Id', "FNMinimiMagazineLarger",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/fnminimi_mag_large",
			'DisplayName', T(354184430796, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarger DisplayName]] "FNMinimi Magazine"),
			'DisplayNamePlural', T(317595853153, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarger DisplayNamePlural]] "FNMinimi Magazines"),
			'Description', T(242577590850, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarger Description]] "Large FNMinimi magazine for 5.56 round"),
			'AdditionalHint', T(266706146245, --[[ModItemInventoryItemCompositeDef FNMinimiMagazineLarger AdditionalHint]] "5.56mm"),
			'Cost', 799,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "MGMags",
			'Platform', "SAW",
			'MagazineSize', 150,
			'Caliber', "556",
			'Modification', "MagLarge",
			'Type', "Large",
			'ExtraAPCosts', 4000,
			'MagReloadCosts', 60000,
			'MagUnloadCosts', 15000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "AA12Magazine",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "Mod/URkxyfE/magpictures/aa_12normal.png",
			'DisplayName', T(920157645577, --[[ModItemInventoryItemCompositeDef AA12Magazine DisplayName]] "AA12 Magazine"),
			'DisplayNamePlural', T(261274054278, --[[ModItemInventoryItemCompositeDef AA12Magazine DisplayNamePlural]] "AA12 Magazines"),
			'Description', T(333799004034, --[[ModItemInventoryItemCompositeDef AA12Magazine Description]] "Standard AA12 magazine"),
			'AdditionalHint', T(945449277810, --[[ModItemInventoryItemCompositeDef AA12Magazine AdditionalHint]] "12gauge"),
			'Cost', 399,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 80,
			'CanBeConsumed', false,
			'CategoryPair', "OtherMags",
			'Platform', "AA12",
			'MagazineSize', 8,
			'Caliber', "12gauge",
			'Modification', "MagNormal",
			'Type', "Rifle",
			'MagReloadCosts', 12000,
			'MagUnloadCosts', 6000,
		}),
		PlaceObj('ModItemInventoryItemCompositeDef', {
			'Group', "Clip",
			'Id', "AA12MagazineLarge",
			'object_class', "Mag",
			'ScrapParts', 3,
			'Repairable', false,
			'Icon', "UI/Icons/Upgrades/aa12_mag_drum",
			'DisplayName', T(372895830190, --[[ModItemInventoryItemCompositeDef AA12MagazineLarge DisplayName]] "AA12 Drum Magazine"),
			'DisplayNamePlural', T(281581449031, --[[ModItemInventoryItemCompositeDef AA12MagazineLarge DisplayNamePlural]] "AA12 Drum Magazines"),
			'Description', T(528516420382, --[[ModItemInventoryItemCompositeDef AA12MagazineLarge Description]] "Drum AA12 magazine"),
			'AdditionalHint', T(946631619926, --[[ModItemInventoryItemCompositeDef AA12MagazineLarge AdditionalHint]] "12gauge"),
			'Cost', 599,
			'CanAppearInShop', true,
			'Tier', 2,
			'RestockWeight', 60,
			'CanBeConsumed', false,
			'CategoryPair', "OtherMags",
			'Platform', "AA12",
			'MagazineSize', 20,
			'Caliber', "12gauge",
			'Modification', "MagLarge",
			'Type', "Large",
			'MagReloadCosts', 20000,
			'MagUnloadCosts', 10000,
		}),
		}),
	PlaceObj('ModItemFolder', {
		'name', "XTemplateMods",
	}, {
		PlaceObj('ModItemCode', {
			'name', "X_WeaponComponentWindow",
			'CodeFileName', "Code/X_WeaponComponentWindow.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "X_Utils",
			'CodeFileName', "Code/X_Utils.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "X_RolloverInventoryBase",
			'CodeFileName', "Code/X_RolloverInventoryBase.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "X_InventoryContextSubMenu",
			'CodeFileName', "Code/X_InventoryContextSubMenu.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "X_InventoryContextMenu",
			'CodeFileName', "Code/X_InventoryContextMenu.lua",
		}),
		PlaceObj('ModItemCode', {
			'name', "X_UIWeaponDisplay",
			'CodeFileName', "Code/X_UIWeaponDisplay.lua",
		}),
		}),
	PlaceObj('ModItemCode', {
		'name', "ReloadMag",
		'CodeFileName', "Code/ReloadMag.lua",
	}),
	PlaceObj('ModItemCode', {
		'name', "ReloadWeapon",
		'CodeFileName', "Code/ReloadWeapon.lua",
	}),
}