return PlaceObj('ModDef', {
	'title', "Revised Mags Module",
	'id', "URkxyfE",
	'author', "Ablomis",
	'version', 98,
	'lua_revision', 233360,
	'saved_with_revision', 340147,
	'code', {
		"Code/AddPlatformToWeapons.lua",
		"Code/LootDefs.lua",
		"Code/MagsItemDefinition.lua",
		"Code/MagsItems.lua",
		"Code/Reload.lua",
		"InventoryItem/MP5MagazineNormal.lua",
		"InventoryItem/AK47Magazine.lua",
		"InventoryItem/AK74Magazine.lua",
		"InventoryItem/AK74MagazineExpanded.lua",
		"InventoryItem/STANAGMagazine.lua",
		"InventoryItem/AUGMagazine.lua",
		"InventoryItem/M14Magazine.lua",
		"InventoryItem/GalilMagazine.lua",
		"InventoryItem/FAMASMagazine.lua",
		"InventoryItem/FNFALMagazine.lua",
		"InventoryItem/AR15Magazine.lua",
		"InventoryItem/GlockMagazine.lua",
		"InventoryItem/UZIMagazine.lua",
		"InventoryItem/SVDMagazine.lua",
		"InventoryItem/HK21Magazine.lua",
		"InventoryItem/FNMinimiMagazine.lua",
		"InventoryItem/BerettaMagazine.lua",
		"InventoryItem/BHPMagazine.lua",
		"InventoryItem/DesertEagleMagazine.lua",
		"InventoryItem/MP40Magazine.lua",
	},
	'saved', 1692660712,
	'code_hash', 2351419486330577372,
})