return PlaceObj('ModDef', {
	'title', "Revised Mags II (Beta)",
	'description', "This is a reworked rerelease of Ablomis' Revised Mags mod. \n\nThis mod adds magazines for weapons to the game. \n\nIt is recommended that you use the Revised Tactical Gear II Mod together with this one but it is not required.\n\nIt is currently in beta which means that:\n\nthere are bugs \nit is not save-game compatible\nit is not compatible with a lot of popular mods\n\nI am looking forward to your bug reports. You can send your savegames to huda0816 in the JA3 modding Discord. Please do not send reports if you are using any other mods (besides Tactical Gear II mod) as I won't have time to investigate compatibility issues at the moment.\n\nInfo for mod creators: I would recommend to wait until you start to make your mod compatible to this one as there could still be major changes.\n\nMore Infos and videos will be added soon.",
	'image', "Mod/URkxyfE/Images/JA3Revised-Mags.png",
	'last_changes', "Fixed bug which caused the bullet count to be shown as 0 when reloading mags",
	'id', "URkxyfE",
	'author', "permanent666",
	'version_minor', 2,
	'version', 12,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/OR_ReloadCombatAction.lua",
		"Code/OR_Misc.lua",
		"Code/OR_HighlightWeaponsForAmmo.lua",
		"Code/OR_MoveItem.lua",
		"Code/OR_Unit.lua",
		"Code/OR_Firearm.lua",
		"Code/ReloadUtils.lua",
		"Code/SETUP_BobbyRays.lua",
		"Code/SETUP_MsgDefs.lua",
		"Code/SETUP_MagsItemDefinition.lua",
		"Code/SETUP_ModOptions.lua",
		"Code/SETUP_AddPlatformAndMagazineToWeapons.lua",
		"Code/SETUP_Config.lua",
		"Code/CMP_RealCalibers.lua",
		"InventoryItem/BHPMagazine.lua",
		"InventoryItem/BHPMagazineLarge.lua",
		"InventoryItem/BerettaMagazine.lua",
		"InventoryItem/BerettaMagazineLarge.lua",
		"InventoryItem/GlockMagazine.lua",
		"InventoryItem/GlockMagazineLarge.lua",
		"InventoryItem/DesertEagleMagazine.lua",
		"InventoryItem/DesertEagleMagazineLarge.lua",
		"InventoryItem/MP5Magazine.lua",
		"InventoryItem/MP5MagazineLarge.lua",
		"InventoryItem/MP40Magazine.lua",
		"InventoryItem/MP40MagazineLarge.lua",
		"InventoryItem/UZIMagazine.lua",
		"InventoryItem/UZIMagazineLarge.lua",
		"InventoryItem/STANAGMagazine.lua",
		"InventoryItem/STANAGMagazineLarge.lua",
		"InventoryItem/AK47Magazine.lua",
		"InventoryItem/AK47MagazineMagLarge.lua",
		"InventoryItem/AK47MagazineMagLarger.lua",
		"InventoryItem/FAMASMagazine.lua",
		"InventoryItem/AUGMagazine.lua",
		"InventoryItem/AUGMagazineLarge.lua",
		"InventoryItem/FNFALMagazine.lua",
		"InventoryItem/FNFALMagazineLarge.lua",
		"InventoryItem/GalilMagazine.lua",
		"InventoryItem/GalilMagazineLarge.lua",
		"InventoryItem/G36MagazineLarge.lua",
		"InventoryItem/G36MagazineQuick.lua",
		"InventoryItem/G36MagazineLarger.lua",
		"InventoryItem/AK74Magazine.lua",
		"InventoryItem/AK74MagazineLarge.lua",
		"InventoryItem/M14Magazine.lua",
		"InventoryItem/M14MagazineLarge.lua",
		"InventoryItem/HKG3Magazine.lua",
		"InventoryItem/HKG3MagazineLarge.lua",
		"InventoryItem/HKG3MagazineLarger.lua",
		"InventoryItem/SVDMagazine.lua",
		"InventoryItem/BarretM82Magazine.lua",
		"InventoryItem/BarretM82MagazineLarge.lua",
		"InventoryItem/FNMinimiMagazineLarge.lua",
		"InventoryItem/FNMinimiMagazineLarger.lua",
		"InventoryItem/AA12Magazine.lua",
		"InventoryItem/AA12MagazineLarge.lua",
		"Code/X_WeaponComponentWindow.lua",
		"Code/X_Utils.lua",
		"Code/X_RolloverInventoryBase.lua",
		"Code/X_InventoryContextSubMenu.lua",
		"Code/X_InventoryContextMenu.lua",
		"Code/X_UIWeaponDisplay.lua",
		"Code/ReloadMag.lua",
		"Code/ReloadWeapon.lua",
		"Code/OR_Inventory.lua",
	},
	'default_options', {
		RevisedMagDropChance = "10",
	},
	'has_data', true,
	'saved', 1710281416,
	'code_hash', -5705248625546336496,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagNormal",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarge",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "WeaponComponent",
			'Id', "MagLarger",
			'ClassDisplayName', "Weapon component",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BHPMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BHPMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BerettaMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BerettaMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "GlockMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "GlockMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "DesertEagleMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "DesertEagleMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MP5Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MP5MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MP40Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "MP40MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "UZIMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "UZIMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "STANAGMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "STANAGMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK47Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK47MagazineMagLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK47MagazineMagLarger",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FAMASMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AUGMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AUGMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNFALMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNFALMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "GalilMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "GalilMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "G36MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "G36MagazineQuick",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "RecipeDef",
			'Id', "G36QuickMag",
			'ClassDisplayName', "Combine recipe",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "G36MagazineLarger",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK74Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AK74MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M14Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "M14MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HKG3Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HKG3MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "HKG3MagazineLarger",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "SVDMagazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BarretM82Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "BarretM82MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNMinimiMagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "FNMinimiMagazineLarger",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AA12Magazine",
			'ClassDisplayName', "Inventory item",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "AA12MagazineLarge",
			'ClassDisplayName', "Inventory item",
		}),
	},
	'steam_id', "3178368899",
	'TagWeapons&Items', true,
})